version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  chatbot:
    build: .
    container_name: chatbot-ui
    ports:
      - "7860:7860"
    depends_on:
      - ollama

volumes:
  ollama_data:
